name: command_line_destripe
channels:
  - defaults
dependencies:
  - bzip2=1.0.8=he774522_0
  - ca-certificates=2023.12.12=haa95532_0
  - certifi=2024.2.2=py311haa95532_0
  - libffi=3.4.4=hd77b12b_0
  - openssl=3.0.13=h2bbff1b_0
  - pip=22.3.1=py311haa95532_0
  - python=3.11.5=he1021f5_0
  - setuptools=65.6.3=py311haa95532_0
  - sqlite=3.41.2=h2bbff1b_0
  - tk=8.6.12=h2bbff1b_0
  - tzdata=2023d=h04d1e81_0
  - vc=14.2=h21ff451_1
  - vs2015_runtime=14.27.29016=h5e58377_2
  - wheel=0.38.4=py311haa95532_0
  - wincertstore=0.2=py311haa95532_0
  - xz=5.4.5=h8cc25b3_0
  - zlib=1.2.13=h8cc25b3_0
  - pip:
      - argcomplete==3.2.2
      - charset-normalizer==2.1.1
      - colorama==0.4.6
      - colorlog==6.8.2
      - cycler==0.11.0
      - dcimg==0.6.0.post1
      - distlib==0.3.8
      - filelock==3.13.1
      - fonttools==4.38.0
      - fsspec==2023.4.0
      - idna==3.4
      - imageio==2.31.2
      - iniconfig==2.0.0
      - jinja2==3.1.2
      - kiwisolver==1.4.5
      - lazy-loader==0.3
      - markupsafe==2.1.3
      - more-itertools==10.2.0
      - mpmath==1.3.0
      - networkx==3.2.1
      - nox==2023.4.22
      - numpy==1.26.4
      - packaging==23.2
      - pathlib2==2.3.7.post1
      - pillow==10.0.1
      - platformdirs==4.2.0
      - pluggy==1.4.0
      - pooch==1.8.0
      - psutil==5.9.8
      - ptwt==0.1.7
      - pyparsing==3.1.1
      - pytest==8.0.0
      - python-dateutil==2.8.2
      - pywavelets==1.5.0
      - pywin32==306
      - requests==2.28.1
      - scikit-image==0.22.0
      - scipy==1.12.0
      - six==1.16.0
      - sympy==1.12
      - tifffile==2024.1.30
      - tqdm==4.64.1
      - typing-extensions==4.8.0
      - urllib3==1.26.13
      - virtualenv==20.25.0
      - tabulate==0.9.0
